version: "3.5"

services:
  "app":
    build: ./app/
    volumes:
      - "./app:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "7001:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_AUTHOR=wiezmankimchi
      - REACT_APP_VER=1.02

  api-gateway:
    build: "./api-gateway"
    depends_on:
      - listing-service
      - users-service
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/usr/src/app
      - "/usr/src/app/node_modules"

  listing-service:
    build: "./listing-service"
    depends_on:
      - listing-service-db
    command: ["./migration.sh"]
    environment:
      # - DB_URI=mysql://root:password@listing-service-db/db?charset=UTF8
      # postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
      - DB_URI=postgresql://root:password@listing-service-db/listing
      - PG_DATABASE=listing
      - PG_USERNAME= root
      - PG_PASSWORD= password
    ports:
      - 7100:7100
    volumes:
      - ./listing-service:/usr/src/app
      - "/usr/src/app/node_modules"

  listing-service-db:
    volumes:
      - ./listing-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: listing
    image: postgres
    ports:
      - 0.0.0.0:7200:5432
  #
  #
  # listing-service-db:
  #   volumes:
  #     - ./listing-db:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=db
  #   image: mysql:5.7.20
  #   ports:
  #     - 0.0.0.0:7200:3306

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    command: ["./migration.sh"]
    environment:
      # - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
      # postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
      - DB_URI=postgresql://root:password@users-service-db/users
      - PG_DATABASE=users
      - PG_USERNAME=root
      - PG_PASSWORD=password
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/usr/src/app
      - "/usr/src/app/node_modules"

  users-service-db:
    volumes:
      - ./users-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: users
    image: postgres
    ports:
      - 0.0.0.0:7201:5432
  #
  #
  # users-service-db:
  #   volumes:
  #     - ./users-db:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=db
  #   image: mysql:5.7.20
  #   ports:
  #     - 0.0.0.0:7201:3306
  # migration:
  #   image: 33c_users-service:latest
  #   command:
  #     [
  #       './wait-for-it/wait-for-it.sh',
  #       'users-service-db:7201',
  #       '--',
  #       'npx',
  #       'sequelize-cli',
  #       'db:migrate',
  #     ]
  #   links:
  #     - users-service-db
  #   depends_on:
  #     - users-service-db
